version: '3.9'

services:
  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    shm_size: '2gb'
    restart: unless-stopped
    environment:
      - "ACCEPT_EULA=1"
      - "SA_PASSWORD=Str0ngPa55w0rd!"
    ports:
      - "1433:1433"
    volumes:
      - "mssql-server-data:/var/opt/mssql"

volumes:
  mssql-server-data:
    driver: local
